#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
#
# $Log: not supported by cvs2svn $
# Revision 1.1  2007/05/02 16:11:40  shang
# first version
#
#
#


TOP=../../../..
include $(TOP)/configure/CONFIG
include $(TOP)/src/SDDS/2d_interpolate/csa/Makefile.OAG
include $(TOP)/configure/RULES
