#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
#
# makefile for namelist
# $Log: not supported by cvs2svn $
# Revision 1.15  2003/07/22 23:25:16  soliday
# Modified makefiles to work with base versions 3.13 and 3.14
#
# Revision 1.14  2003/05/06 19:05:51  soliday
# Changed CFLAGS on Solaris so that it would use the reentrant flag.
#
# Revision 1.13  2003/02/20 16:18:54  soliday
# Makefiles now work to build static builds on windows.
#
# Revision 1.12  2002/12/08 02:32:55  borland
# Fixed problems with commands inside namelist items under CONDOR.
# Also, added fclose() for the popen() implementation of the command
# feature.
#
# Revision 1.11  2002/08/14 16:23:48  soliday
# Added Open License
#
# Revision 1.10  2002/07/30 08:40:57  soliday
# Changed the purify lines.
#
# Revision 1.9  2000/12/07 22:00:15  jba
# Changes for building with base R3.14.
#
# Revision 1.8  2000/10/04 19:45:22  soliday
# Shared libraries are now allowed on operating systems other then WIN32
#
# Revision 1.7  2000/08/11 19:30:43  soliday
# Overrode -mt (multithreaded) compile line option on Solaris when using cc.
#
# Revision 1.6  2000/08/10 21:14:55  soliday
# Added support for gcc on Solaris.
#
# Revision 1.5  2000/04/04 04:59:10  soliday
# Added warning flag for solaris.
#
# Revision 1.4  1999/10/05 21:36:17  borland
# Increased print buffer sizes from 1024 to 16384 bytes.
#
# Revision 1.3  1999/07/08 20:50:46  soliday
# Added support for WIN32
#
# Revision 1.2  1999/06/01 19:13:02  borland
# Replaced CNL_CutOutComments with version from SDDS library.
#
# Revision 1.1  1999/04/14 15:14:46  borland
# First version added to repository (per J. Anderson).
#
#

TOP = ../../../..
include $(TOP)/config/CONFIG_EXTENSIONS
include $(TOP)/src/SDDS/namelist/Makefile.OAG
ifdef WIN32
LIBNAME = namelist.lib
endif
include $(TOP)/config/RULES.Host

