#
# $Log: Makefile,v $
# Revision 1.2  1999/04/14 14:04:53  borland
# Works with new build system.  Fixed some missing prototypes and function type mismatches.
#
# Revision 1.1  1997/02/10 19:37:43  saunders
# Initial work on oosdds.
#
# Revision 1.1  1995/09/05 21:10:37  saunders
# First test release of the SDDS1.5 package.
#
#
#  Lowest Level Directroy Makefile
#
#

TOP=../../..

include $(TOP)/config/CONFIG_EXTENSIONS

include $(TOP)/config/RULES_ARCHS

