/*
 *
 $Log: not supported by cvs2svn $
 *
 */
#define HCLXmInit HCLXmInit_BC
#define XmCreateMainWindow XmCreateMainWindow_BC
#define XmCreateMenuBar XmCreateMenuBar_BC
#define XmCreateCascadeButton XmCreateCascadeButton_BC
#define XmCreateForm XmCreateForm_BC
#define XmCreateDrawingArea XmCreateDrawingArea_BC
#define XmMainWindowSetAreas XmMainWindowSetAreas_BC
#define XmCreateWarningDialog XmCreateWarningDialog_BC
#define XmUpdateDisplay XmUpdateDisplay_BC
#define XmTextGetString XmTextGetString_BC
#define XmCreateScrolledText XmCreateScrolledText_BC
#define XmTextSetString XmTextSetString_BC
#define XmCreatePulldownMenu XmCreatePulldownMenu_BC
#define XmCreateOptionMenu XmCreateOptionMenu_BC
#define XmStringCreateSimple XmStringCreateSimple_BC
#define XmCreatePromptDialog XmCreatePromptDialog_BC
#define XmSelectionBoxGetChild XmSelectionBoxGetChild_BC
#define XmStringGetLtoR XmStringGetLtoR_BC
#define XmToggleButtonGetState XmToggleButtonGetState_BC
#define XmCreateFormDialog XmCreateFormDialog_BC
#define XmCreateSeparator XmCreateSeparator_BC
#define XmCreateTextField XmCreateTextField_BC
#define XmStringCreate XmStringCreate_BC
#define XmCreateLabel XmCreateLabel_BC
#define XmCreateSimpleRadioBox XmCreateSimpleRadioBox_BC
#define XmCreateToggleButton XmCreateToggleButton_BC
#define XmToggleButtonSetState XmToggleButtonSetState_BC
#define XmCreateRowColumn XmCreateRowColumn_BC
#define XmCreatePushButton XmCreatePushButton_BC
#define XmTextFieldGetString XmTextFieldGetString_BC
#define XmStringCreateLtoR XmStringCreateLtoR_BC
#define XmCreateInformationDialog XmCreateInformationDialog_BC
#define XmStringFree XmStringFree_BC
#define XmMessageBoxGetChild XmMessageBoxGetChild_BC
