# makefile for Exceed wrapper DLL
# $Log: not supported by cvs2svn $
#
#

TOP = ../../../../../..
include $(TOP)/config/CONFIG_EXTENSIONS

CMPLR=ANSI
#HOST_OPT=NO

LIBRARY = hclsdds
INC = hclsdds.h
USR_CFLAGS = 	-I../../../../include -I$(MOTIF_INC) \
		-I$(X11_INC) -DWIN32 -D_WINDOWS \
		$(EXCEED_CFLAGS)

PROD_LIBS = $(EXCEED_XLIBS)

LIBSRCS += wrapper.c

include $(TOP)/config/RULES.Host


