#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
#
# makefile for SDDS applications
# $Log: not supported by cvs2svn $
# Revision 1.4  2003/02/20 16:18:54  soliday
# Makefiles now work to build static builds on windows.
#
# Revision 1.3  2003/02/19 21:00:03  soliday
# Fixed problems compiling with Borland C
#
# Revision 1.2  2002/08/14 17:27:01  soliday
# Added Open License
#
# Revision 1.1  2001/03/23 21:25:58  soliday
# This version replaces the version that required Exceed to run on WIN32.
#
#

TOP = ../../../../../..
include $(TOP)/config/CONFIG_EXTENSIONS
include $(TOP)/src/SDDS/SDDSaps/sddsplots/winMotifDriver/Makefile.OAG
include $(TOP)/config/RULES.Host


