#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
#
# makefile for mdbcommon
# $Log: not supported by cvs2svn $
# Revision 1.4  2003/08/28 22:12:30  soliday
# Cleaned up the code.
#
# Revision 1.3  2002/08/14 16:48:27  soliday
# Added Open License
#
# Revision 1.2  2002/07/30 08:55:26  soliday
# Added logfile_gener.c
#
# Revision 1.1  2000/04/19 18:48:49  soliday
# First version of Makefile.Vx
#
#
#
#

TOP = ../../../..
include $(TOP)/config/CONFIG_EXTENSIONS

USR_CFLAGS += -I../../include

SRCS.c = \
	../fixcounts.c ../findfiles.c ../interpMinimum.c ../lincorr.c \
	../logfile_gener.c ../lsfg.c ../lsfn.c \
	../lsfp.c ../savitzkyGolay.c ../scanargs.c \
	../table.c

LIBOBJS = \
	fixcounts.o findfiles.o interpMinimum.o lincorr.o \
	logfile_gener.o lsfg.o lsfn.o \
	lsfp.o savitzkyGolay.o scanargs.o \
	table.o

LIBNAME = mdbcommon

include $(TOP)/config/RULES.Vx

