//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mpl_motif.rc
//
#define IDC_MYICON                      2
#define IDD_TEST33_DIALOG               102
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDS_HELLO                       106
#define IDI_TEST33                      107
#define IDI_MPLMOTIF                    107
#define IDI_SMALL                       108
#define IDC_TEST33                      109
#define IDC_MPLMOTIF                    109
#define IDS_UNKNOWNFILETYPE             110
#define IDS_INVALIDDRAWCOMMAND          111
#define IDS_OUTOFLOOP                   112
#define IDS_ERRORREADINGINPUT           113
#define IDS_UNABLESAVEIMAGE             114
#define IDS_FILEORPIPEERROR             115
#define IDR_MAINFRAME                   128
#define IDD_CONTENTSBOX                 129
#define IDD_SETUPBOX                    133
#define IDD_NAVIGATE_NUMBER             135
#define IDD_MOUSETRACKER                136
#define IDD_COLOR                       138
#define IDD_SAVEAS                      141
#define IDD_ERRORBOX                    142
#define ID_CONTENTS_REMOVE              1002
#define IDC_EDIT1                       1007
#define ID_SETUP_REMOVE                 1009
#define IDC_EDIT2                       1010
#define IDC_RADIO5                      1016
#define IDC_RADIO6                      1017
#define IDC_RADIO7                      1018
#define IDC_RADIO8                      1019
#define IDC_CHECK1                      1020
#define IDC_RADIO9                      1023
#define IDC_RADIO10                     1024
#define IDC_RADIO11                     1025
#define IDC_RADIO12                     1026
#define IDC_RADIO13                     1028
#define IDC_SETUP_PRINT                 1029
#define IDC_EDIT4                       1032
#define IDC_RADIO16                     1033
#define IDC_RADIO17                     1034
#define IDC_CHECK2                      1035
#define IDC_RADIO18                     1036
#define IDC_RADIO19                     1037
#define IDC_RADIO20                     1038
#define IDC_RADIO21                     1039
#define IDC_RADIO22                     1040
#define IDC_RADIO23                     1041
#define IDC_BUTTON5                     1042
#define IDC_SETUP_PRINTCOMMAND          1043
#define IDC_COMBO1                      1044
#define IDC_EDIT3                       1046
#define IDC_EDIT5                       1047
#define IDC_EDIT6                       1048
#define IDC_EDIT7                       1049
#define IDC_EDIT8                       1050
#define IDC_EDIT9                       1051
#define IDC_BLACKONWHITE                1052
#define IDC_WHITEONBLACK                1053
#define IDC_SPECTRUMLINES               1054
#define IDC_GROUPLINES                  1103
#define IDC_LANDSCAPE                   1108
#define IDC_PORTRAIT                    1109
#define IDC_BLACKANDWHITE               1110
#define IDC_COLOR                       1111
#define IDC_BORDER                      1112
#define ID_FILE_SETUP                   32771
#define ID_FILE_PRINTSETUP              32772
#define ID_FILE_SAVE                    32773
#define ID_FILE_DUMP                    32774
#define ID_NAVIGATE_NEXT                32775
#define ID_NAVIGATE_PREVIOUS            32776
#define ID_NAVIGATE_DELETE              32777
#define ID_NAVIGATE_TONUMBER            32778
#define ID_OPTIONS_ZOOM_IN              32780
#define ID_OPTIONS_ZOOM_OUT             32781
#define ID_OPTIONS_ZOOM_UP              32782
#define ID_OPTIONS_ZOOM_DOWN            32783
#define ID_OPTIONS_ZOOM_LEFT            32784
#define ID_OPTIONS_ZOOM_RIGHT           32785
#define ID_OPTIONS_ZOOM_RESTORE         32786
#define ID_OPTIONS_ZOOM_HELP            32787
#define ID_OPTIONS_PLACEMENT_FULLSCREEN 32788
#define ID_OPTIONS_PLACEMENT_FIRSTQUARTER 32789
#define ID_OPTIONS_PLACEMENT_SECONDQUARTER 32790
#define ID_OPTIONS_PLACEMENT_THIRDQUARTER 32791
#define ID_OPTIONS_PLACEMENT_FOURTHQUARTER 32792
#define ID_OPTIONS_PLACEMENT_TOPHALF    32793
#define ID_OPTIONS_PLACEMENT_BOTTOMHALF 32794
#define ID_OPTIONS_PLACEMENT_LEFTHALF   32795
#define ID_OPTIONS_PLACEMENT_RIGHTHALF  32796
#define ID_OPTIONS_MOVE                 32797
#define ID_OPTIONS_MOVIE                32797
#define ID_OPTIONS_GREYSCALE            32798
#define ID_OPTIONS_DOUBLEBUFFER         32799
#define ID_OPTIONS_CONFIRMFILE          32800
#define ID_OPTIONS_MOUSETRACKER         32801
#define ID_OPTIONS_COLOR                32802
#define ID_CONTENTS                     32803
#define ID_OPTIONS_PLACEMENT_CENTER     32804
#define ID_FILE_PRINT                   32809
#define ID_FILE_SAVEAS                  32810
#define ID_NAVIGATE_FIRST               32812
#define ID_NAVIGATE_LAST                32813
#define ID_EXIT                         32814
#define ID_OPTIONS_PLACEMENT_FIRSTQUARTER_F1 32815
#define ID_OPTIONS_PLACEMENT_SECONDQUARTER_F2 32816
#define ID_OPTIONS_PLACEMENT_THIRDQUARTER_F3 32817
#define ID_OPTIONS_PLACEMENT_FOURTHQUARTER_F4 32818
#define ID_OPTIONS_DASHES               32819
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32820
#define _APS_NEXT_CONTROL_VALUE         1113
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
