#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
#
# Top Makefile for Java SDDS software
# $Log: not supported by cvs2svn $
# Revision 1.4  2002/08/14 19:32:39  soliday
# Added Open License
#
# Revision 1.3  2001/06/05 18:46:24  soliday
# Moved SDDSaccessories into SDDS.
#
# Revision 1.2  2000/05/09 21:20:35  soliday
# Added SDDSplot
#
# Revision 1.1  2000/05/01 14:25:59  soliday
# First version.
#
#
#

TOP = ../../..
include $(TOP)/configure/CONFIG

DIRS = SDDS SDDSedit SDDS3Dplot

include $(TOP)/configure/RULES_DIRS
