#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
#
# makefile for fdlibm
# $Log: not supported by cvs2svn $
# Revision 1.6  2003/07/18 19:57:02  soliday
# Added support for Kylix.
#
# Revision 1.5  2002/08/14 15:49:49  soliday
# Added Open License
#
# Revision 1.4  2000/04/21 20:15:26  soliday
# Added Bessel function for Borland C.
#
# Revision 1.3  2000/04/19 16:04:43  soliday
# Added NO_BORLAND_STDC to remove the STDC definition from the compile line.
#
# Revision 1.2  1999/09/14 18:08:26  soliday
# On WIN32 a dll file is now created.
#
# Revision 1.1  1999/07/12 19:45:12  soliday
# Makefile.Host for customized fdlibm library used with WIN32.
# This library is used to create erf, erfc, and lgamma functions for Visual C++
#
#

TOP = ../../../..

NO_BORLAND_STDC=1
include $(TOP)/config/CONFIG_EXTENSIONS
include $(TOP)/src/SDDS/fdlibm/Makefile.OAG
include $(TOP)/config/RULES.Host
